### ISSUE TITLE
Further data arrangement of map visualization

### ISSUE THREAD

**Issue by WANG-yingxuan** [Wuuw12/DataScience-G9#5]
Please sort out the brick and tile factories in the **top 10** areas of Scotland with their names, time of establishment, and the appearance and photos of the bricks and tiles

**Comment by WANG-yingxuan** [comment]
There are TOP 10 areas and the number of occurrences
[('Glasgow', 144),
 ('North Lanarkshire', 88),
 ('South Lanarkshire', 72),
 ('Stirlingshire', 62),
 ('Fife', 54),
 ('East Ayrshire', 44),
 ('Falkirk', 40),
 ('North Ayrshire', 38),
 ('West Lothian', 31),
 ('East Lothian', 30)]

**Comment by WANG-yingxuan** [comment]
The latest correction, November 29, the website has been updated
[('Glasgow', 145),
 ('North Lanarkshire', 89),
 ('South Lanarkshire', 72),
 ('Stirlingshire', 63),
 ('Fife', 55),
 ('East Ayrshire', 44),
 ('Falkirk', 41),
 ('North Ayrshire', 38),
 ('East Lothian', 30),
 ('West Lothian', 30)]

**Comment by DI-ZHUhaixia** [comment]
**I collect from 15-21 (one is wrong) here is the brief information,and I will upload the files of images of each brick.**

'Stirlingshire'  
Greenhill Fireclay Company, 1860 – Brickworks started?, 20 bricks/tiles collected

'South Lanarkshire'
Ibstock Scottish Brick Limited, 1972, 1brick
Larkhall Brickfields, 1896, 8bricks

'East Ayrshire'
Southhook Fireclay Works, 1901, 49bricks

'Glasgow'
William Baird and Co Ltd, 1818, 7bricks

'North Lanarkshire'
Wishaw Brickworks, 1844, 3 bricks

**Comment by Wuuw12** [comment]
I find urls of brick images of factories from top 8-14:

**Carfin Brickworks, Lanarkshire**
https://www.scottishbrickhistory.co.uk/greenhill-16/ 
 https://www.scottishbrickhistory.co.uk/greenhill-15/

**Carfin Colliery Brickworks, Lanarkshire**
https://www.scottishbrickhistory.co.uk/ibstock/    
https://www.scottishbrickhistory.co.uk/a-r-4/

**Coltness Brickworks Limited, North Lanarkshire**
https://www.scottishbrickhistory.co.uk/bramall/ 
 https://www.scottishbrickhistory.co.uk/caledonian/

**Craigton Brickworks, Glasgow**
https://www.scottishbrickhistory.co.uk/southhook-bonnyton-kilmarnock/  
 https://www.scottishbrickhistory.co.uk/j-gilmour-co-kilmarnock-2/  

**Crown Fire Clay Works, Glasgow**
https://www.scottishbrickhistory.co.uk/white-hill/

**Drongan Pottery, East Ayrshire**
https://www.scottishbrickhistory.co.uk/b-ss/  
https://www.scottishbrickhistory.co.uk/ncb-annbank/
