### ISSUE TITLE
Repeating facoties in the file Data_location_Top10.csv

### ISSUE THREAD

**Issue by DI-ZHUhaixia** [Wuuw12/DataScience-G9#6]
@Valerie-Zhao 
I found that there are some repeating factories names in the cav file.

**Comment by Valerie-Zhao** [comment]
Yes, will do the cleaning again!

**Comment by Valerie-Zhao** [comment]
[Top10_location_correct.xlsx](https://github.com/Wuuw12/DataScience-G9/files/5631236/Top10_location_correct.xlsx)
Try this file. I actually fail to figure out how to clean them using Python or other coding tools. So just directly delete the repeating data in Excel. But should be fine I think
