### ISSUE TITLE
Any advice for the tool of the interactive website

### ISSUE THREAD

**Issue by Valerie-Zhao** [Wuuw12/DataScience-G9#7]
Hi All, @DI-ZHUhaixia @Wuuw12 @WANG-yingxuan I am trying to build an interactive website since our time is limited, I find this tool www.wix.com/, which is very easy and no coding. I think we can use this to do. But our original idea is to make an interactive map, I'm afraid this couldn't be realized, any suggestion? or any recommendation for the tool?
![Wix](https://user-images.githubusercontent.com/72869583/100912477-6ce54380-34c8-11eb-8ddc-cc3932d684b8.png)

**Comment by DI-ZHUhaixia** [comment]
I think **ArcGIs StoryMaps** is a great tool that we can use to create a website with geo-visulisation.  I tries these before, it doesn't  require code skills. This could give us more functions to choose and the map is also interactive. Here is the link [ArcGIs StoryMaps](https://storymaps.arcgis.com/)

**Comment by Valerie-Zhao** [comment]
Cool! Will try it
